const CONSTANTS = {
  GET_POSTS: "GET_POSTS",
  SET_POSTS: "SET_POSTS",
  ERROR_POSTS: "ERROR_POSTS",

  GET_POST: "GET_POST",
  SET_POST: "SET_POST",
  UPDATE_POST: "UPDATE_POST",
  CLEAR_POST: "CLEAR_POST",
  ERROR_POST: "ERROR_POST",
};

export default CONSTANTS;
